'use strict';
const api = window.crewrouterDesktop;
const dict = { zh: { title:'Desktop 设置', connection:'当前连接', profiles:'连接 Profiles', localServer:'Local Server', preferences:'Desktop 偏好', diagnostics:'诊断信息', diagnosticsHint:'仅包含安全白名单字段，不包含 Token 或 API Key。', copy:'复制诊断信息', copied:'已复制', unavailable:'Desktop 设置桥接不可用，请重启应用。', restart:'安全重启', stop:'停止', autoConnect:'启动时自动连接上次 Profile', notifications:'启用桌面通知', updateChecks:'检查更新', theme:'主题', system:'跟随系统', light:'浅色', dark:'深色', rename:'重命名', delete:'删除', active:'当前', mode:'模式', target:'目标地址', runtime:'运行时', edition:'版本', status:'状态', pid:'进程 ID', port:'端口', ready:'运行中', stopped:'已停止', none:'无', confirmStop:'确定停止本地 Server？', remoteNote:'Remote Desktop 设置暂未开放；当前仅支持可信 Local Desktop。' }, en: { title:'Desktop Settings', connection:'Current connection', profiles:'Connection profiles', localServer:'Local Server', preferences:'Desktop preferences', diagnostics:'Diagnostics', diagnosticsHint:'Only an allowlisted summary is included; tokens and API keys are never stored or copied.', copy:'Copy diagnostics', copied:'Copied', unavailable:'The Desktop settings bridge is unavailable. Please restart the app.', restart:'Safe restart', stop:'Stop', autoConnect:'Connect to the last profile on startup', notifications:'Enable desktop notifications', updateChecks:'Check for updates', theme:'Theme', system:'Follow system', light:'Light', dark:'Dark', rename:'Rename', delete:'Delete', active:'Active', mode:'Mode', target:'Target', runtime:'Runtime', edition:'Edition', status:'Status', pid:'PID', port:'Port', ready:'Running', stopped:'Stopped', none:'None', confirmStop:'Stop the local Server?', remoteNote:'Remote Desktop settings are not available yet; only trusted Local Desktop is supported.' } };
const required = ['getDesktopSettings','saveDesktopSettings','renameProfile','deleteProfile','stopLocal','getDiagnostics'];
const restartLocal = () => window.crewrouterDesktop?.restartLocal?.();
let lang = 'zh'; let data; let available = required.every((key) => typeof api?.[key] === 'function');
const $ = (id) => document.getElementById(id); const t = (key) => dict[lang][key] || key;
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function applyTheme(value) { const scheme = value === 'system' ? (window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : value; document.documentElement.dataset.bloraColorScheme = scheme; }
function render() { if (!data) return; document.querySelectorAll('[data-i18n]').forEach((el) => { el.textContent = t(el.dataset.i18n); }); const s = data.status || {}; $('connection').innerHTML = [['mode', s.mode], ['target', s.target], ['runtime', s.runtime], ['edition', s.edition]].map(([k,v])=>`<dt>${t(k)}</dt><dd>${escapeHtml(v || t('none'))}</dd>`).join(''); const local = data.local; $('local-card').hidden = s.runtime !== 'desktop-local' && !data.status.localProfile; $('local').innerHTML = local ? `<dt>${t('pid')}</dt><dd>${escapeHtml(local.pid || t('none'))}</dd><dt>${t('port')}</dt><dd>${escapeHtml(local.port || t('none'))}</dd><dt>${t('status')}</dt><dd>${local.ready ? t('ready') : t('stopped')}</dd>` : `<dt>${t('status')}</dt><dd>${t('stopped')}</dd>`; $('profiles').innerHTML = data.profiles.map((p) => `<div class="profile"><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.url)} ${p.id === s.profile?.id ? t('active') : ''}</small></span><button data-rename="${escapeHtml(p.id)}">${t('rename')}</button><button data-delete="${escapeHtml(p.id)}" class="danger">${t('delete')}</button></div>`).join('') || `<p class="muted">${t('none')}</p>`; $('autoConnect').checked = data.settings.autoConnect; $('notifications').checked = data.settings.notifications; $('updateChecks').checked = data.settings.updateChecks; $('theme').value = data.settings.theme; applyTheme(data.settings.theme); $('remote-note').hidden = s.mode !== 'remote'; }
async function action(fn) { try { return await fn(); } catch (error) { $('message').textContent = error?.message || String(error); return null; } }
async function reload() { data = await api.getDesktopSettings(); render(); }
function disableUnavailable() { document.querySelectorAll('button,select,input').forEach((el) => { el.disabled = true; }); $('message').textContent = t('unavailable'); }
(async () => { lang = localStorage.getItem('desktop-language') || 'zh'; $('language').value = lang; if (!available) { document.querySelectorAll('[data-i18n]').forEach((el) => { el.textContent = t(el.dataset.i18n); }); disableUnavailable(); return; } try { await reload(); } catch { available = false; disableUnavailable(); return; } $('language').onchange = (e) => { lang=e.target.value; localStorage.setItem('desktop-language',lang); render(); }; ['autoConnect','notifications','updateChecks','theme'].forEach(id => $(id).addEventListener('change', () => action(async () => { data.settings = await api.saveDesktopSettings({ autoConnect:$('autoConnect').checked, notifications:$('notifications').checked, updateChecks:$('updateChecks').checked, theme:$('theme').value }); applyTheme(data.settings.theme); }))); $('restart').onclick = () => action(async () => { await restartLocal(); await reload(); }); $('stop').onclick = () => { if (confirm(t('confirmStop'))) action(async () => { await api.stopLocal(); await reload(); }); }; $('copy').onclick = () => action(async () => { await navigator.clipboard.writeText(JSON.stringify(await api.getDiagnostics(), null, 2)); $('message').textContent=t('copied'); }); $('profiles').onclick = (e) => action(async () => { const rename=e.target.dataset.rename, del=e.target.dataset.delete; if (rename) { const name=prompt(t('rename'), data.profiles.find(p=>p.id===rename)?.name); if(name) await api.renameProfile(rename,name); } else if (del && confirm(`${t('delete')}?`)) await api.deleteProfile(del); await reload(); }); const media = window.matchMedia?.('(prefers-color-scheme: dark)'); media?.addEventListener?.('change', () => { if ($('theme').value === 'system') applyTheme('system'); }); })();